{{- if .Values.queues }}
{{- range $queue := .Values.queues }}
---
apiVersion: oldmonk.evalsocket.in/v1
kind: QueueAutoScaler
metadata:
  name: {{ template "oldmonk.fullname" $ }}-queue-{{ $queue.name | replace "_" "-"}}
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ $queue.type | quote }}
  policy: {{ $queue.policy | quote }}
  {{- if $queue.targetMessagesPerWorker }}
  targetMessagesPerWorker: {{ $queue.targetMessagesPerWorker }}
  {{- end }}
  {{- if $queue.option }}
  option:
    {{- $queue.option | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  minPods: {{ $queue.minPods }}
  maxPods: {{ $queue.maxPods }}
  scaleDown:
    amount: {{ $queue.scaleDown.amount }}
    threshold: {{ $queue.scaleDown.threshold }}
  scaleUp:
    amount: {{ $queue.scaleUp.amount }}
    threshold: {{ $queue.scaleUp.threshold }}
  deployment: {{ $queue.deployment }}
  {{- if $queue.labels }}
  labels:
    {{- $queue.labels | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  autopilot: {{ $queue.autopilot }}
  secrets: "{{ template "oldmonk.fullname" $ }}-queue-{{ $queue.name | replace "_" "-"}}"
{{ end }}
{{ end }}